### ISSUE TITLE
Add CLI option to set cookie in `~/.config/aocpy/token`

### ISSUE THREAD

**Issue by eruvanos** [SteadBytes/aocpy#11]
As a user,
I want to set the cookie using cli command
So that I do not have to create the folders and token file myself.

Proposal:
`aocpy set-cookie <cookie>`

- Creates folders if they do not exists
- write `<cookie>` to token file

**Comment by SteadBytes** [comment]
Thanks for opening this issue - I agree this would be a handy feature. I'll take a look at your PR 👍
